from models_app.admin.user.resources import UserAdmin
from models_app.admin.user_project.resources import UserProjectAdmin
from models_app.admin.timer.resources import TimerAdmin
from models_app.admin.task_user.resources import TaskUserAdmin
from models_app.admin.task.resources import TaskAdmin
from models_app.admin.subtask.resources import SubtaskAdmin
from models_app.admin.project.resources import ProjectAdmin
from models_app.admin.dashboard.resources import DashboardAdmin
from models_app.admin.comment.resources import CommentAdmin
from models_app.admin.document.resources import DocumentAdmin
