# Generated by Django 4.0 on 2023-10-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_dashboard_project_task_taskuser_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='projects/', verbose_name='Фото проекта'),
            preserve_default=False,
        ),
    ]
