# Generated by Django 4.0 on 2023-10-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
