# Generated by Django 4.0 on 2023-10-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_dashboard_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='project',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards_project', to='models_app.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
