# Generated by Django 4.0 on 2023-10-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_dashboard_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7, verbose_name='Цвет'),
        ),
    ]
