# Generated by Django 4.0 on 2023-11-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_subtask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_author', to='models_app.user', verbose_name='Менеджер задачи'),
            preserve_default=False,
        ),
    ]
