# Generated by Django 4.0 on 2024-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0012_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
    ]
