name: Deploy

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Connect to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_IP }}
        username: somebody
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: ansible-playbook ./deploy.yml -v -i ${{ secrets.DEPLOYMENT_IP }}, --extra-vars="project=somebody"