name: Deploy

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Create temporary SSH key file
      run: |
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > /tmp/private_key
        chmod 600 /tmp/private_key

        - name: Run Ansible playbook
          run: |
            ansible-playbook ./deploy.yml -v -i ${{ secrets.DEPLOYMENT_IP }}, --extra-vars "project=somebody"
          env:
            ANSIBLE_HOST_KEY_CHECKING: 'false'
            ANSIBLE_REMOTE_USER: somebody
            ANSIBLE_PRIVATE_KEY_FILE: /tmp/private_key